task:
  freebsd_instance:
    matrix:
      - image_family: freebsd-13-2-snap
      - image_family: freebsd-14-0-snap
  deps_script:
    - sed -i.bak -e 's/quarterly/latest/' /etc/pkg/FreeBSD.conf
    - env ASSUME_ALWAYS_YES=yes pkg update -f
    - env ASSUME_ALWAYS_YES=yes pkg install -y llvm11 gmake z3 cmake pkgconf google-perftools python3 py39-sqlite3 py39-tabulate nlohmann-json bash coreutils immer
  build_script:
    - mkdir build
    - cd build
    - cmake -DLLVM_DIR=/usr/local/llvm11 -DMAKE_BINARY=/usr/local/bin/gmake -DJSON_SRC_DIR=/usr/local -DIMMER_SRC_DIR=/usr/local -DENABLE_TCMALLOC:BOOL=true -DENABLE_POSIX_RUNTIME:BOOL=ON -DENABLE_SOLVER_Z3:BOOL=true -DENABLE_SYSTEM_TESTS:BOOL=ON ..
    - gmake
  test_script:
    - sed -i.bak -e 's/lit\./lit11\./' test/lit.cfg
    - cd build
    - gmake check
task:
  macos_instance:
    matrix:
      - image_family: macos-ventura-xcode:N:latest
      - image_family: macos-sonoma-xcode:N:latest
  environment:
      BASE: /tmp
      SOLVERS: STP
      UCLIBC_VERSION: 0
      USE_TCMALLOC: 0
      USE_LIBCXX: 0
  deps_script:
    - brew install bash
  build_script:
    - scripts/build/build.sh klee --debug --install-system-deps
  test_script:
    - scripts/build/run-tests.sh /tmp/klee_build* --debug
